name:                mixlogue
version:             0.2.0
homepage:            https://github.com/matsubara0507/mixlogue#readme
license:             MIT
author:              MATSUBARA Nobutada
maintainer:          t12307043@gunma-u.ac.jp
copyright:           MATSUBARA Nobutada
category:            Web
description:         Please see the README on GitHub at <https://github.com/matsubara0507/mixlogue#readme>

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -optP-Wno-nonportable-include-path

default-extensions:
- NoImplicitPrelude

- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiWayIf
- NumericUnderscores
- OverloadedLabels
- OverloadedStrings
- PolyKinds
- QuasiQuotes
- RankNTypes
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances

dependencies:
- base >= 4.7 && < 5
- rio >= 0.1.1.0
- extensible >= 0.6
- extensible-elmap
- aeson
- blaze-html
- elmap
- fallible
- http-api-data
- mix
- mix-json-logger
- req >= 2.0.0
- servant-blaze
- servant-server
- slackell
- unliftio
- warp

library:
  source-dirs: src

executables:
  mixlogue:
    main: Main.hs
    source-dirs: app/mixlogue
    dependencies:
    - mixlogue
    - dotenv

tests:
  generateElm:
    main: GenerateElm.hs
    source-dirs: test
    dependencies:
    - mixlogue
    - servant-elmap
    - shelly
    other-modules: []
