resolver: lts-14.22
packages:
- '.'
extra-deps:
- elm-bridge-0.5.2
- membership-0
- github: fumieval/extensible
  commit: d197daaef0ae18b9734384b8f0efa5783bc629e9
- req-3.0.0
- retry-0.8.1.0
- servant-elm-0.7.1
- github: matsubara0507/mix.hs
  commit: c6c303f9ddf4655a42804ee67d512af6d3b14e98
  subdirs:
  - mix
  - mix-json-logger
- github: matsubara0507/fallible
  commit: 4a7d965fc8128640ec750b28f7df49be88448286
- github: matsubara0507/elmap.hs
  commit: a1539c3be6e8b5757a2a10a55e7c1b19c1fc76fd
  subdirs:
  - elmap
  - extensible-elmap
  - servant-elmap
- github: matsubara0507/slackell
  commit: 6c8aeefa4c44be4f70537bb9879756d53b705c94
  subdirs:
  - .
  - lib/simple-api
