resolver: lts-13.24
packages:
- '.'
extra-deps:
- extensible-0.5
- req-2.0.1
- retry-0.8.0.1
- github: matsubara0507/mix.hs
  commit: 2138a7a5a43443040893134f1170ce1643f0d498
  subdirs:
  - mix
  - mix-json-logger
